
- name: Install Kubernetes packages
  hosts: k8s_cluster
  become: true

  tasks:
    - name: Add Kubernetes v1.36 repository
      ansible.builtin.copy:
        dest: /etc/yum.repos.d/kubernetes.repo
        mode: '0644'
        content: |
          [kubernetes]
          name=Kubernetes
          baseurl=https://pkgs.k8s.io/core:/stable:/v1.36/rpm/
          enabled=1
          gpgcheck=1
          gpgkey=https://pkgs.k8s.io/core:/stable:/v1.36/rpm/repodata/repomd.xml.key
          exclude=kubelet kubeadm kubectl cri-tools kubernetes-cni

    - name: Install kubelet kubeadm and kubectl
      ansible.builtin.dnf:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: present
        disable_excludes: kubernetes

    - name: Enable kubelet
      ansible.builtin.systemd:
        name: kubelet
        enabled: true

    - name: Check whether firewalld is installed
      ansible.builtin.package_facts:
        manager: auto

    - name: Disable and stop firewalld
      ansible.builtin.systemd:
        name: firewalld
        enabled: false
        state: stopped
      when: "'firewalld' in ansible_facts.packages"
